apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  # 此字段的值需要和主题文件夹名称一致，否则可能导致部分资源无法正常加载。
  name: blog-theme--main
spec:
  displayName: TalkMe Blog Theme
  author:
    name: TalkMe
    website: https://talkme.ai
  description: TalkMe博客主题，基于Halo 2.0，集成现代化的语言学习博客设计
  logo: https://blog.talkme.ai/wp-content/uploads/2025/05/talkme-logo.png
  homepage: https://blog.talkme.ai
  repo: https://github.com/talkme/talkme-blog-theme
  issues: https://github.com/talkme/talkme-blog-theme/issues
  settingName: "blog-theme--main-setting"
  configMapName: "blog-theme--main-configMap"
  version: "1.0.0"
  requires: ">=2.0.0"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/talkme/talkme-blog-theme/blob/main/LICENSE"

